name: Build CI
run-name: Build app and upload artifact
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - run: ./gradlew build
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - uses: actions/upload-artifact@v3
        with:
          name: Unbuttoned-App.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      - run: cd /tmp && git clone https://github.com/unbuttoned-app/unbuttoned-releases.git
      - run: cp ${{steps.sign_app.outputs.signedReleaseFile}} /tmp/Unbuttoned-App.apk
      - run: sudo apt update && sudo apt install fdroidserver
      - run: cd /tmp/unbuttoned-releases && cp /tmp/Unbuttoned-App.apk repo/
      - run: cd /tmp/unbuttoned-releases && echo "${{ secrets.CONFIG_B64}}" | base64 --decode > config.yml
      - run: cd /tmp/unbuttoned-releases && echo "${{ secrets.REPO_KS_B64}}" | base64 --decode > keystore.p12 
      - run: cd /tmp/unbuttoned-releases && rm -f repo/.NOTE && fdroid update -c && git config user.name root && git config user.email "root@localhost"
      - run: cd /tmp/unbuttoned-releases && git add repo && git commit -m "update" && git push origin main

